- name: Configure system
  hosts: linux_local
  become: yes
  tasks:
    - name: Update current system
      community.general.pacman:
        update_cache: true
        upgrade: true

    - name: Configure git
      ansible.builtin.shell: |
        git config --global core.autocrlf input
        git config --global credential.credentialStore secretservice

    - name: Install essential applications
      community.general.pacman:
        name:
          - git-lfs
          - cmake
          - fastfetch
          - htop

    - name: Install main applications
      community.general.pacman:
        name:
          - ibus-bamboo
          - stow
          - fish
          - wezterm
          - code
          - wl-clipboard
          - neovim
          - lazygit

    - name: Install fonts
      community.general.pacman:
        name:
          - ttf-jetbrains-mono-nerd
          - ttf-nerd-fonts-symbols-mono
          - ttf-lilex-nerd

