[mgr]
ratio = [1, 4, 4]
linemode = "size"

[preview]
wrap = "yes"

[opener]
edit = [
    { run = "nvim %s", block = true, orphan = true },
]

edit_dir = [
    { run = "nvim %d", block = true, orphan = true, desc = "Nvim in directory"}
]

[open]
rules = [
    { mime = "*/", use = ["edit", "edit_dir", "open", "reveal"] },
    { mime = "text/*", use = ["edit", "edit_dir", "reveal"] },
]
